## Nornir Groups File 
---
CSR: 
  username: cisco
  password: cisco
  platform: ios
  port: 22

NOKIA:
  username: admin
  password: admin
  platform: alcatel_sros
  port: 22
  data:
    target: candidate
  connection_options:
    scrapli_netconf:
      port: 830
      username: netconf  
      password: NCadmin123
      extras:
        auth_strict_key: False
      platform: alu

IOSXR:
  username: htinoco
  password: admin
  platform: iosxr
  port: 22
  data:
    target: candidate
  connection_options:
    scrapli_netconf:
      port: 830
      username: htinoco
      password: admin
      extras:
        ssh_config_file: False
        auth_strict_key: False
  
IOS:
  username: cisco
  password: cisco
  platform: ios
  port: 22
  